### PR TITLE
Initial work towards cross-platform compatibility

### PR DESCRIPTION
**Pull request by akien-mga**
Hi there,

I've tried to build Vinctus Arce on Linux (Mageia 5 64bit) with GCC 4.9.2, and run into some issues.
* 37c6c16 fixes the include path to use only the conventional slash directory delimiter instead of the Windows-specific backslash.
* cf2727c fixes an "extra qualification" error which Visual Studio seems not to bother about, but other compilers do: http://stackoverflow.com/questions/5642367/extra-qualification-error-in-c

I'm still not sure if this is enough to get the game to work on Linux, as I couldn't find yet the right way to compile the game properly (I get the files to compile, but I don't get the linker flags right to actually generate the binary). I'll have to learn how to write a proper makefile first :)

### CODE REVIEW

**Comment by Sand3r-** [comment]
I haven't tried compiling it on the linux yet unfortunately - therefore there is not much I can do, althoguh in the near future I'll try to do so, although the changes made are approved, thank you for contributing.

**Comment by akien-mga** [comment]
Thanks :) I now have a working Makefile (though it currently uses the Linux shell to find all *.cpp files, so it might not work out of the box on Windows, but since you don't use GNU make currently... ;)), I'll make a PR for it.

**Comment by Sand3r-** [comment]
The multiplatform solution would be to use premake4, or a cmake list which are able to generate files compatible with both Linux and Windows (and Mac as well I believe). I'm gonna accept the linux-specific makefile as for now though.

**Comment by akien-mga** [comment]
> The multiplatform solution would be to use premake4, or a cmake list which are able to generate files compatible with both Linux and Windows (and Mac as well I believe). I'm gonna accept the linux-specific makefile as for now though.

Yes, I have some experience with CMake that we're using in @OpenDungeons, I could probably work on a CMake buildsystem later on. But for now I'm going with the quick and dirty way to see if the game can actually run on Linux :)

**Pull request merged**
